#!/bin/sh
make clean
make PLATFORM=PC
cd output
./simplemenu-x86
# check memory leak issues
#valgrind --leak-check=full ./simplemenu-x86
#valgrind --leak-check=full --show-leak-kinds=all ./simplemenu-x86
#valgrind -s ./simplemenu-x86
cd ..
