#!/bin/sh
cd ~/git/invoker/invoker
make clean
make PLATFORM=NPG
cp ~/git/invoker/invoker/invoker.dge ~/git/simplemenu-esmode/simplemenu/output/invoker.dge
cd ~/git/simplemenu-esmode/simplemenu/
make clean
make PLATFORM=NPG
cd output
./make_opk.sh NPG
while true; do
    read -p "Transfer?" yn
    case $yn in
        [Yy]* ) scp SimpleMenu.opk root@10.1.1.2:/media/data/apps; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
