#!/bin/sh
cd ~/git/invoker/invoker
make clean
make PLATFORM=OD
cp ~/git/invoker/invoker/invoker.dge ~/git/simplemenu-esmode/simplemenu/output/invoker.dge
cd ~/git/simplemenu-esmode/simplemenu/
make clean
make PLATFORM=OD
cd output
./make_opk.sh OD
while true; do
    read -p "Transfer?" yn
    case $yn in
        [Yy]* ) scp SimpleMenu-OD.opk root@10.1.1.2:/media/RG350/apps/SimpleMenu-OD.opk; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
